name: public-redis
services:
  redis:
    image: redis:latest
    container_name: public-redis
    ports:
      - "6379:6379"
    volumes:
      # 挂载 Redis 配置文件
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      # 挂载数据目录（持久化）
      - ./redis-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
